apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  DB_NAME: otus-app
  DB_USER: otus
---
apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  DB_PASSWORD: b3R1cw==
  DB_URI: cG9zdGdyZXNxbDovL290dXM6b3R1c0Bwb3N0Z3Jlcy9vdHVzLWFwcA==
# postgresql://otus:otus@postgres/otus-app
  JDBC_DB_URI: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMvb3R1cy1hcHA=
# jdbc:postgresql://postgres:5432/otus-app
