apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: docker-service
          image: hexist/firstimage:0.0.5
          env:
            - name: spring.datasource.url
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: JDBC_DB_URI
            - name: spring.datasource.username
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DB_USER
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: DB_PASSWORD
          ports:
            - name: web
              containerPort: 8000
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 3
            periodSeconds: 5

